import React, { useState } from "react";

import {
  ScrollView,
  TextInput,
  Text,
  StyleSheet,
  Image,
  View,
  ImageBackground,
  Pressable,
  TouchableOpacity,
} from "react-native";
import { useNavigation } from "@react-navigation/native";
import BouncyCheckbox from "react-native-bouncy-checkbox";
import {Calendar, CalendarList, Agenda, Header} from 'react-native-calendars';
const StudyPlan = () => {
  const [tasks, setTasks] = useState([{ selected: false, name: "Study Java" }]);
  const [newTaskName, onChangeName] = useState("");
  const navigation = useNavigation();

  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

  return (
    <View style={styles.studyPlanView}>
      <Text style={styles.yourStudyPlan}>Your Study Plan</Text>
      <Text style={styles.w3SchoolsText}>W3Schools</Text>
      <View style={styles.calendarView}>
        <Calendar
          theme={{
            selectedDayBackgroundColor: '#FF4F00',
            arrowColor: '#FF4F00',
          }}
          onDayPress={(day) => {
            console.log("selected day", day);
          }}
          onDayLongPress={(day) => {
            console.log("selected day", day);
          }}
          monthFormat={"yyyy MM"}
          onMonthChange={(month) => {
            console.log("month changed", month);
          }}
          firstDay={1}
          onPressArrowLeft={(subtractMonth) => subtractMonth()}
          onPressArrowRight={(addMonth) => addMonth()}
          // Disable all touch events for disabled days. can be override with disableTouchEvent in markedDates
          disableAllTouchEventsForDisabledDays={true}
        />
      </View>
      <View style={styles.tODOLISTView}>
        <Text style={styles.toDoText}>To Do:</Text>
        <ImageBackground
          style={styles.frameIcon}
          resizeMode="cover"
          source={require("../assets/frame5.png")}
        >
          <View style={styles.toDoList}>
            <ScrollView style={{ maxHeight: 160 }}>
              {tasks.map((task) => (
                <View style={{ marginTop: 5, width: 100 }}>
                  <BouncyCheckbox
                    size={18}
                    fillColor="#FF4F00"
                    text={task.name}
                    iconStyle={{ borderColor: "#FF4F00" }}
                    innerIconStyle={{ borderWidth: 2 }}
                    textStyle={{ fontFamily: "Raleway" }}
                    onPress={(isChecked) => {
                      setTasks((pv) => {
                        const index = pv.findIndex((t) => t.name === task.name);
                        const filtered = pv.filter((t, idx) => idx !== index);
                        return filtered;
                      });
                    }}
                  />
                </View>
              ))}
            </ScrollView>
            <TextInput
              style={styles.input}
              value={newTaskName}
              onChangeText={onChangeName}
              placeholder="Task name"
              keyboardType="default"
            />
            <TouchableOpacity
              style={styles.button}
              onPress={() => {
                if (newTaskName === "") return;
                setTasks((p) => [...p, { selected: false, name: newTaskName }]);
                onChangeName("");
              }}
            >
              <Text style={styles.btnText}>Add</Text>
            </TouchableOpacity>
          </View>
        </ImageBackground>
      </View>
      <View style={styles.frameView2}>
        <Text style={styles.yourProgressText}>Your progress:</Text>
        <View style={styles.frameView}>
          <View style={styles.sliderView1}>
            <View style={styles.sliderView}>
              <View style={styles.trackView} />
              <View style={styles.changeValueView}>
                <View style={styles.spacerView} />
                <Image
                  style={[styles.knobIcon, styles.ml100]}
                  resizeMode="cover"
                  source={require("../assets/knob.png")}
                />
              </View>
            </View>
          </View>
          <Text style={styles.jAVAText}>JAVA</Text>
          <TouchableOpacity
            style={styles.jcTouchableOpacity}
            activeOpacity={0.2}
            onPress={() => navigation.navigate("JavaINTRODUCTION")}
          >
            <View style={styles.jAVACOURSEView} />
            <Text style={styles.continueJavaCourse}>Continue Java Course</Text>
          </TouchableOpacity>
        </View>
        <View style={styles.frameView1}>
          <View style={styles.sliderView3}>
            <View style={styles.sliderView2}>
              <View style={styles.trackView1} />
              <View style={styles.changeValueView1}>
                <View style={styles.spacerView1} />
              </View>
              <Image
                style={styles.knobIcon1}
                resizeMode="cover"
                source={require("../assets/knob1.png")}
              />
            </View>
          </View>
          <Text style={styles.pythonText}>Python</Text>
          <TouchableOpacity
            style={styles.pcTouchableOpacity}
            activeOpacity={0.2}
            onPress={() => navigation.navigate("PythonIntroduction")}
          >
            <View style={styles.pYTHONCOURSEView} />
            <Text style={styles.continuePythonCourse}>
              Continue Python Course
            </Text>
          </TouchableOpacity>
        </View>
      </View>
      <View style={styles.searchFieldView}>
        <Image
          style={styles.iconMagnifyingglass}
          resizeMode="cover"
          source={require("../assets/icon--magnifyingglass.png")}
        />
        <Text style={[styles.placeholderText, styles.ml6]}>Search</Text>
        <Image
          style={[styles.sFSymbolMicrophone, styles.ml6]}
          resizeMode="cover"
          source={require("../assets/sf-symbol--microphone.png")}
        />
      </View>
      <View style={styles.navigationView}>
        <View style={styles.navView} />
        <TouchableOpacity
          style={styles.iconOutlinehomeTouchableOpacity}
          activeOpacity={0.2}
          onPress={() => navigation.navigate("LoggedInHomePage")}
        >
          <Image
            style={styles.icon}
            resizeMode="cover"
            source={require("../assets/icon2.png")}
          />
          <Text style={styles.homeText}>home</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.iconSolidbookOpenTouchableOpacity}
          activeOpacity={0.2}
          onPress={() => navigation.navigate("Courses")}
        >
          <Image
            style={styles.icon1}
            resizeMode="cover"
            source={require("../assets/icon8.png")}
          />
          <Text style={styles.coursesText}>courses</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.iconOutlinepencilAltTouchableOpacity}
          activeOpacity={0.2}
          onPress={() => navigation.navigate("StudyPlan")}
        >
          <Image
            style={styles.icon2}
            resizeMode="cover"
            source={require("../assets/icon4.png")}
          />
          <Text style={styles.agendaText}>agenda</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.iconOutlineacademicCapTouchableOpacity}
          activeOpacity={0.2}
          onPress={() => navigation.navigate("Quizzes")}
        >
          <Image
            style={styles.icon3}
            resizeMode="cover"
            source={require("../assets/icon5.png")}
          />
          <Text style={styles.quizzesText}>quizzes</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.iconSoliduserCircleTouchableOpacity}
          activeOpacity={0.2}
          onPress={() => navigation.navigate("Profile")}
        >
          <Image
            style={styles.icon4}
            resizeMode="cover"
            source={require("../assets/icon6.png")}
          />
          <Text style={styles.profileText}>profile</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  ml8: {
    marginLeft: 8,
  },
  ml6: {
    marginLeft: 6,
  },
  ml100: {
    marginLeft: 100,
  },
  button: {
    marginTop: 10,
    backgroundColor: "rgba(255, 79, 0, 0.66)",
    border: "1px solid #FFFFFF",
    width: 100,
    alignItems: "center",
    alignSelf: "center",
  },
  btnText: {
    alignItems: "center",
    fontSize: 13,
    letterSpacing: 0.38,
    lineHeight: 24,
    color: "#ffffff",
  },
  yourStudyPlan: {
    position: "absolute",
    top: 136,
    left: 10,
    fontSize: 20,
    fontFamily: "Raleway",
    color: "#ff4f00",
    textAlign: "left",
  },
  w3SchoolsText: {
    position: "absolute",
    top: 59,
    left: 10,
    fontSize: 35,
    fontWeight: "700",
    fontFamily: "Raleway",
    color: "#ff4f00",
    textAlign: "left",
    width: 194,
    height: 44,
  },
  monthText: {
    position: "relative",
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontWeight: "700",
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "left",
  },
  sFIconChevronforward: {
    position: "relative",
    width: 6.69,
    height: 11.44,
    flexShrink: 0,
  },
  monthYear: {
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  sFSymbolChevronbackward: {
    position: "relative",
    width: 9.97,
    height: 17.32,
    flexShrink: 0,
  },
  sFSymbolChevronforward: {
    position: "relative",
    width: 9.97,
    height: 17.32,
    flexShrink: 0,
  },
  frameIcon: {
    position: "absolute",
    top: 51,
    left: 11,
    width: 163,
    height: 270,
    overflow: "hidden",
  },
  arrowsView: {
    width: 51,
    flexShrink: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  monthPickerView: {
    position: "absolute",
    top: 8,
    right: 16,
    left: 16,
    height: 44,
    flexDirection: "row",
    paddingHorizontal: 0,
    paddingVertical: 7,
    boxSizing: "border-box",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dayText: {
    position: "absolute",
    marginTop: -9,
    marginLeft: -13,
    top: "50%",
    left: "50%",
    fontSize: 13,
    letterSpacing: -0.08,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: "Atkinson Hyperlegible",
    color: "rgba(60, 60, 67, 0.3)",
    textAlign: "center",
  },
  dayView: {
    position: "relative",
    width: 32,
    height: 18,
    flexShrink: 0,
  },
  dayText1: {
    position: "absolute",
    marginTop: -9,
    marginLeft: -15.5,
    top: "50%",
    left: "50%",
    fontSize: 13,
    letterSpacing: -0.08,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: "Atkinson Hyperlegible",
    color: "rgba(60, 60, 67, 0.3)",
    textAlign: "left",
  },
  dayView1: {
    position: "relative",
    width: 32,
    height: 18,
    flexShrink: 0,
  },
  dayText2: {
    position: "absolute",
    marginTop: -9,
    marginLeft: -12,
    top: "50%",
    left: "50%",
    fontSize: 13,
    letterSpacing: -0.08,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: "Atkinson Hyperlegible",
    color: "rgba(60, 60, 67, 0.3)",
    textAlign: "center",
  },
  dayView2: {
    position: "relative",
    width: 32,
    height: 18,
    flexShrink: 0,
  },
  dayText3: {
    position: "absolute",
    marginTop: -9,
    marginLeft: -14.5,
    top: "50%",
    left: "50%",
    fontSize: 13,
    letterSpacing: -0.08,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: "Atkinson Hyperlegible",
    color: "rgba(60, 60, 67, 0.3)",
    textAlign: "center",
  },
  dayView3: {
    position: "relative",
    width: 32,
    height: 18,
    flexShrink: 0,
  },
  dayText4: {
    position: "absolute",
    marginTop: -9,
    marginLeft: -13,
    top: "50%",
    left: "50%",
    fontSize: 13,
    letterSpacing: -0.08,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: "Atkinson Hyperlegible",
    color: "rgba(60, 60, 67, 0.3)",
    textAlign: "center",
  },
  input: {
    backgroundColor: "rgba(255, 255, 255, 0.60)",
    height: 30,
    marginLeft: 20,
    marginTop: 15,
    paddingHorizontal: 5,
  },
  dayView4: {
    position: "relative",
    width: 32,
    height: 18,
    flexShrink: 0,
  },
  dayText5: {
    position: "absolute",
    marginTop: -9,
    marginLeft: -11.5,
    top: "50%",
    left: "50%",
    fontSize: 13,
    letterSpacing: -0.08,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: "Atkinson Hyperlegible",
    color: "rgba(60, 60, 67, 0.3)",
    textAlign: "center",
  },
  dayView5: {
    position: "relative",
    width: 32,
    height: 18,
    flexShrink: 0,
  },
  dayText6: {
    position: "absolute",
    marginTop: -9,
    marginLeft: -12,
    top: "50%",
    left: "50%",
    fontSize: 13,
    letterSpacing: -0.08,
    lineHeight: 18,
    fontWeight: "700",
    fontFamily: "Atkinson Hyperlegible",
    color: "rgba(60, 60, 67, 0.3)",
    textAlign: "center",
  },
  dayView6: {
    position: "relative",
    width: 32,
    height: 18,
    flexShrink: 0,
  },
  calendarDayRowView: {
    position: "absolute",
    top: 56,
    right: 16,
    left: 16,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  dateText: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "none",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText1: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "none",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView1: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText2: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView2: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText3: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView3: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText4: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView4: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText5: {
    position: "absolute",
    marginTop: -16,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
    height: 32,
  },
  digitView5: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText6: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView6: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  calendarDayRowView1: {
    position: "absolute",
    top: 84,
    right: 16,
    left: 16,
    flexDirection: "row",
    paddingHorizontal: 0,
    paddingVertical: 10,
    boxSizing: "border-box",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  dateText7: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView7: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText8: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontWeight: "700",
    fontFamily: "Atkinson Hyperlegible",
    color: "#fff",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView8: {
    position: "relative",
    borderRadius: 100,
    backgroundColor: "#ff3b30",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText9: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView9: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText10: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView10: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText11: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView11: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText12: {
    position: "absolute",
    marginTop: -16,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
    height: 32,
  },
  digitView12: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText13: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView13: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  calendarDayRowView2: {
    position: "absolute",
    top: 132,
    right: 16,
    left: 16,
    flexDirection: "row",
    paddingHorizontal: 0,
    paddingVertical: 10,
    boxSizing: "border-box",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  dateText14: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView14: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText15: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView15: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText16: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView16: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText17: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView17: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText18: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView18: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText19: {
    position: "absolute",
    marginTop: -16,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
    height: 32,
  },
  digitView19: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText20: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView20: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  calendarDayRowView3: {
    position: "absolute",
    top: 180,
    right: 16,
    left: 16,
    flexDirection: "row",
    paddingHorizontal: 0,
    paddingVertical: 10,
    boxSizing: "border-box",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  dateText21: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView21: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText22: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView22: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText23: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView23: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText24: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView24: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText25: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView25: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText26: {
    position: "absolute",
    marginTop: -16,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
    height: 32,
  },
  digitView26: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText27: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView27: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  calendarDayRowView4: {
    position: "absolute",
    top: 228,
    right: 16,
    left: 16,
    flexDirection: "row",
    paddingHorizontal: 0,
    paddingVertical: 10,
    boxSizing: "border-box",
    alignItems: "flex-start",
    justifyContent: "space-between",
    display: "none",
  },
  dateText28: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView28: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText29: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView29: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText30: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView30: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText31: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView31: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText32: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "none",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView32: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText33: {
    position: "absolute",
    marginTop: -16,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "none",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
    height: 32,
  },
  digitView33: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  dateText34: {
    position: "absolute",
    marginTop: -12,
    top: "50%",
    left: 0,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff3b30",
    textAlign: "center",
    display: "none",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
  },
  digitView34: {
    position: "relative",
    width: 32,
    height: 32,
    flexShrink: 0,
  },
  calendarDayRowView5: {
    position: "absolute",
    top: 276,
    right: 16,
    left: 16,
    flexDirection: "row",
    paddingHorizontal: 0,
    paddingVertical: 10,
    boxSizing: "border-box",
    alignItems: "flex-start",
    justifyContent: "space-between",
    display: "none",
  },
  timeText: {
    position: "relative",
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontWeight: "700",
    fontFamily: "Atkinson Hyperlegible",
    color: "#000",
    textAlign: "left",
  },
  text: {
    position: "absolute",
    marginTop: -13,
    marginLeft: 9.5,
    top: "50%",
    left: "50%",
    fontSize: 22,
    letterSpacing: 0.35,
    lineHeight: 28,
    fontFamily: "Atkinson Hyperlegible",
    color: "#000",
    textAlign: "right",
  },
  text1: {
    position: "absolute",
    marginTop: -15,
    marginLeft: -0.5,
    top: "50%",
    left: "50%",
    fontSize: 22,
    letterSpacing: 0.35,
    lineHeight: 28,
    fontFamily: "Atkinson Hyperlegible",
    color: "#000",
    textAlign: "right",
  },
  text2: {
    position: "absolute",
    marginTop: -13,
    marginLeft: -32.5,
    top: "50%",
    left: "50%",
    fontSize: 22,
    letterSpacing: 0.35,
    lineHeight: 28,
    fontFamily: "Atkinson Hyperlegible",
    color: "#000",
    textAlign: "right",
    width: 28,
    height: 28,
  },
  centerView: {
    position: "absolute",
    marginTop: -15,
    marginLeft: -32,
    top: "50%",
    left: "50%",
    width: 65,
    height: 30,
  },
  calendarTimePickerView: {
    position: "relative",
    borderRadius: 6,
    backgroundColor: "rgba(118, 118, 128, 0.12)",
    width: 86,
    height: 36,
    flexShrink: 0,
    overflow: "hidden",
  },
  separatorView: {
    position: "absolute",
    height: "55.41%",
    width: "0.56%",
    top: "20.78%",
    right: "3.15%",
    bottom: "23.82%",
    left: "96.29%",
    borderRadius: 0.5,
    backgroundColor: "rgba(60, 60, 67, 0.36)",
    display: "none",
  },
  labelText: {
    position: "absolute",
    marginTop: -8.5,
    top: "50%",
    left: 8,
    fontSize: 13,
    letterSpacing: -0.08,
    lineHeight: 20,
    fontWeight: "700",
    fontFamily: "Atkinson Hyperlegible",
    color: "#000",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 33,
    height: 16,
  },
  segmentedPickerOptionView: {
    alignSelf: "stretch",
    flex: 1,
    position: "relative",
    borderRadius: 6.93,
    backgroundColor: "#fff",
    shadowColor: "rgba(0, 0, 0, 0.12)",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowRadius: 8,
    elevation: 8,
    shadowOpacity: 1,
    borderStyle: "solid",
    borderColor: "rgba(0, 0, 0, 0.04)",
    borderWidth: 0.5,
  },
  separatorView1: {
    position: "absolute",
    height: "57.14%",
    width: "0.57%",
    top: "21.43%",
    right: "1.15%",
    bottom: "21.44%",
    left: "98.28%",
    borderRadius: 0.5,
    backgroundColor: "rgba(60, 60, 67, 0.36)",
    display: "none",
  },
  labelText1: {
    position: "absolute",
    marginTop: -8,
    top: "50%",
    left: 8,
    fontSize: 13,
    letterSpacing: -0.08,
    lineHeight: 20,
    fontWeight: "700",
    fontFamily: "Atkinson Hyperlegible",
    color: "#000",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 33,
    height: 16,
  },
  segmentedPickerOptionView1: {
    alignSelf: "stretch",
    flex: 1,
    position: "relative",
  },
  segmentedPickerView: {
    alignSelf: "stretch",
    borderRadius: 8.91,
    backgroundColor: "rgba(118, 118, 128, 0.12)",
    width: 101,
    flexShrink: 0,
    overflow: "hidden",
    flexDirection: "row",
    padding: 2,
    boxSizing: "border-box",
    alignItems: "flex-start",
    justifyContent: "flex-start",
  },
  timeView: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  timePickerView: {
    position: "absolute",
    right: -1.5,
    bottom: 0,
    left: 0.5,
    flexDirection: "row",
    padding: 16,
    boxSizing: "border-box",
    alignItems: "center",
    justifyContent: "space-between",
    display: "none",
  },
  calendarView: {
    position: "absolute",
    top: 540,
    left: 45,
    backgroundColor: "#fff",
    shadowColor: "rgba(0, 0, 0, 0.1)",
    shadowOffset: {
      width: 0,
      height: 10,
    },
    width: 340,
    height: 240,
  },
  toDoList: {
    marginTop: 20,
  },
  toDoText: {
    position: "absolute",
    top: 16,
    left: 11,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontWeight: "700",
    fontFamily: "Atkinson Hyperlegible",
    color: "#FF4F00",
    textAlign: "left",
  },
  tODOLISTView: {
    position: "absolute",
    top: 180,
    left: 18,
    backgroundColor: "rgba(255, 79, 0, 0.18)",
    borderStyle: "solid",
    borderColor: "rgba(224, 41, 44, 0.75)",
    borderWidth: 1,
    width: 186,
    height: 349,
    overflow: "hidden",
  },
  yourProgressText: {
    position: "absolute",
    top: 15,
    left: 11,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontWeight: "700",
    fontFamily: "Atkinson Hyperlegible",
    color: "rgba(224, 41, 44, 0.05)",
    textAlign: "left",
  },
  trackView: {
    position: "absolute",
    marginTop: -2,
    top: "50%",
    right: 0,
    left: 0,
    borderRadius: 2,
    backgroundColor: "rgba(120, 120, 128, 0.2)",
    height: 4,
  },
  spacerView: {
    position: "relative",
    borderRadius: 2,
    width: 0.01,
    height: 4,
    flexShrink: 0,
  },
  knobIcon: {
    position: "relative",
    width: 43,
    height: 42,
    flexShrink: 0,
  },
  changeValueView: {
    position: "absolute",
    top: 12,
    left: 0,
    borderRadius: 2,
    backgroundColor: "#fff",
    height: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  sliderView: {
    alignSelf: "stretch",
    position: "relative",
    height: 28,
    flexShrink: 0,
  },
  sliderView1: {
    position: "absolute",
    top: 25,
    left: -11,
    width: 196,
    height: 34,
    flexDirection: "column",
    paddingHorizontal: 16,
    paddingVertical: 8,
    boxSizing: "border-box",
    alignItems: "flex-start",
    justifyContent: "flex-start",
  },
  jAVAText: {
    position: "absolute",
    top: 11,
    left: 3,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff4f00",
    textAlign: "left",
  },
  jAVACOURSEView: {
    position: "absolute",
    top: 0,
    left: 0,
    backgroundColor: "rgba(255, 79, 0, 0.66)",
    borderStyle: "solid",
    borderColor: "#fff",
    borderWidth: 1,
    width: 155,
    height: 31,
  },
  cal: {
    backgroundColor: '#ffffff',
    calendarBackground: '#ffffff',
    textSectionTitleColor: '#ffff',
    textSectionTitleDisabledColor: '#d9e1e8',
    selectedDayBackgroundColor: '#00adf5',
    selectedDayTextColor: '#ffffff',
    todayTextColor: '#00adf5',
    dayTextColor: '#2d4150',
    textDisabledColor: '#d9e1e8',
    dotColor: '#00adf5',
    selectedDotColor: '#ffffff',
    arrowColor: 'orange',
    disabledArrowColor: '#d9e1e8',
    monthTextColor: 'blue',
    indicatorColor: 'blue',
    textDayFontFamily: 'monospace',
    textMonthFontFamily: 'monospace',
    textDayHeaderFontFamily: 'monospace',
    textDayFontWeight: '300',
    textMonthFontWeight: 'bold',
    textDayHeaderFontWeight: '300',
    textDayFontSize: 16,
    textMonthFontSize: 16,
    textDayHeaderFontSize: 16
  },
  continueJavaCourse: {
    position: "absolute",
    top: 4,
    left: 11,
    fontSize: 13,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#fff",
    textAlign: "left",
  },
  jcTouchableOpacity: {
    position: "absolute",
    top: 73,
    left: 7,
    width: 155,
    height: 31,
  },
  frameView: {
    position: "absolute",
    top: 46,
    left: 8,
    borderStyle: "solid",
    borderColor: "#ff4f00",
    borderWidth: 1,
    width: 169,
    height: 133,
    overflow: "hidden",
  },
  trackView1: {
    position: "absolute",
    marginTop: -2,
    top: "50%",
    right: 0,
    left: 0,
    borderRadius: 2,
    backgroundColor: "rgba(120, 120, 128, 0.2)",
    height: 4,
  },
  spacerView1: {
    position: "relative",
    borderRadius: 2,
    width: 0.01,
    height: 4,
    flexShrink: 0,
  },
  changeValueView1: {
    position: "absolute",
    top: 12,
    left: 0,
    borderRadius: 2,
    backgroundColor: "#fff",
    width: 66,
    height: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  knobIcon1: {
    position: "absolute",
    marginTop: -15,
    top: "50%",
    right: 73,
    width: 43,
    height: 42,
  },
  sliderView2: {
    alignSelf: "stretch",
    position: "relative",
    height: 28,
    flexShrink: 0,
  },
  sliderView3: {
    position: "absolute",
    top: 25,
    left: -11,
    width: 196,
    height: 34,
    flexDirection: "column",
    paddingHorizontal: 16,
    paddingVertical: 8,
    boxSizing: "border-box",
    alignItems: "flex-start",
    justifyContent: "flex-start",
  },
  pythonText: {
    position: "absolute",
    top: 11,
    left: 3,
    fontSize: 20,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#ff4f00",
    textAlign: "left",
  },
  pYTHONCOURSEView: {
    position: "absolute",
    top: 0,
    left: 0,
    backgroundColor: "rgba(255, 79, 0, 0.65)",
    borderStyle: "solid",
    borderColor: "#fff",
    borderWidth: 1,
    width: 155,
    height: 31,
  },
  continuePythonCourse: {
    position: "absolute",
    top: 3,
    left: 9,
    fontSize: 13,
    letterSpacing: 0.38,
    lineHeight: 24,
    fontFamily: "Atkinson Hyperlegible",
    color: "#fff",
    textAlign: "left",
  },
  pcTouchableOpacity: {
    position: "absolute",
    top: 83,
    left: 7,
    width: 155,
    height: 31,
  },
  frameView1: {
    position: "absolute",
    top: 188,
    left: 8,
    borderStyle: "solid",
    borderColor: "#ff4f00",
    borderWidth: 1,
    width: 169,
    height: 151,
    overflow: "hidden",
  },
  frameView2: {
    position: "absolute",
    top: 180,
    left: 228,
    backgroundColor: "rgba(255, 79, 0, 0.18)",
    borderStyle: "solid",
    borderColor: "rgba(224, 41, 44, 0.75)",
    borderWidth: 1,
    width: 186,
    height: 349,
  },
  iconMagnifyingglass: {
    position: "relative",
    width: 15.63,
    height: 15.78,
    flexShrink: 0,
  },
  placeholderText: {
    flex: 1,
    position: "relative",
    fontSize: 17,
    letterSpacing: -0.41,
    lineHeight: 22,
    fontFamily: "Atkinson Hyperlegible",
    color: "rgba(60, 60, 67, 0.6)",
    textAlign: "left",
  },
  sFSymbolMicrophone: {
    position: "relative",
    width: 11.88,
    height: 17.68,
    flexShrink: 0,
  },
  searchFieldView: {
    position: "absolute",
    top: 63,
    left: 212,
    borderRadius: 10,
    backgroundColor: "rgba(118, 118, 128, 0.12)",
    width: 211,
    flexDirection: "row",
    paddingHorizontal: 8,
    paddingVertical: 7,
    boxSizing: "border-box",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  navView: {
    position: "absolute",
    top: 0,
    left: 0,
    backgroundColor: "#e33b3d",
    width: 430,
    height: 62,
  },
  icon: {
    position: "absolute",
    height: "66.67%",
    width: "78.17%",
    top: "0%",
    right: "11.36%",
    bottom: "33.33%",
    left: "10.47%",
    maxWidth: "100%",
    overflow: "hidden",
    maxHeight: "100%",
  },
  homeText: {
    position: "absolute",
    top: 33,
    left: 13,
    fontSize: 12,
    letterSpacing: -0.24,
    lineHeight: 16,
    fontFamily: "Raleway",
    color: "#fff",
    textAlign: "center",
  },
  iconOutlinehomeTouchableOpacity: {
    position: "absolute",
    top: 11,
    left: 23,
    width: 63.04,
    height: 50,
    overflow: "hidden",
  },
  icon1: {
    position: "absolute",
    height: "56.92%",
    width: "72.73%",
    top: "20%",
    right: "17.27%",
    bottom: "23.08%",
    left: "10%",
    maxWidth: "100%",
    overflow: "hidden",
    maxHeight: "100%",
  },
  coursesText: {
    position: "absolute",
    width: "123.64%",
    top: "81.82%",
    left: "-10.91%",
    fontSize: 12,
    letterSpacing: -0.24,
    lineHeight: 12,
    fontFamily: "Raleway",
    color: "#fff",
    textAlign: "center",
  },
  iconSolidbookOpenTouchableOpacity: {
    position: "absolute",
    height: "88.71%",
    width: "12.88%",
    top: "1.61%",
    right: "62.3%",
    bottom: "9.68%",
    left: "24.82%",
    overflow: "hidden",
  },
  icon2: {
    position: "absolute",
    height: "68%",
    width: "73.97%",
    top: "0%",
    right: "6.01%",
    bottom: "32%",
    left: "20.01%",
    maxWidth: "100%",
    overflow: "hidden",
    maxHeight: "100%",
  },
  agendaText: {
    position: "absolute",
    top: "70%",
    left: "10%",
    fontSize: 12,
    letterSpacing: -0.24,
    lineHeight: 12,
    fontFamily: "Raleway",
    color: "#fff",
    textAlign: "center",
  },
  iconOutlinepencilAltTouchableOpacity: {
    position: "absolute",
    height: "80.65%",
    width: "11.71%",
    top: "12.9%",
    right: "45.2%",
    bottom: "6.45%",
    left: "43.09%",
    overflow: "hidden",
  },
  icon3: {
    position: "absolute",
    height: "67.27%",
    width: "78.64%",
    top: "9.09%",
    right: "12.27%",
    bottom: "23.64%",
    left: "9.09%",
    maxWidth: "100%",
    overflow: "hidden",
    maxHeight: "100%",
  },
  quizzesText: {
    position: "absolute",
    top: "78.18%",
    left: "12.73%",
    fontSize: 12,
    letterSpacing: -0.24,
    lineHeight: 12,
    fontFamily: "Raleway",
    color: "#fff",
    textAlign: "center",
  },
  iconOutlineacademicCapTouchableOpacity: {
    position: "absolute",
    top: 3,
    left: 263,
    width: 55,
    height: 55,
    overflow: "hidden",
  },
  icon4: {
    position: "absolute",
    height: "76.36%",
    width: "76.36%",
    top: "0%",
    right: "14.55%",
    bottom: "23.64%",
    left: "9.09%",
    maxWidth: "100%",
    overflow: "hidden",
    maxHeight: "100%",
  },
  profileText: {
    position: "absolute",
    top: "78.18%",
    left: "20%",
    fontSize: 12,
    letterSpacing: -0.24,
    lineHeight: 12,
    fontFamily: "Raleway",
    color: "#fff",
    textAlign: "center",
  },
  iconSoliduserCircleTouchableOpacity: {
    position: "absolute",
    height: "88.71%",
    width: "12.88%",
    top: "8.06%",
    right: "5.85%",
    bottom: "3.23%",
    left: "81.26%",
    overflow: "hidden",
  },
  navigationView: {
    position: "absolute",
    top: 868,
    left: -9,
    borderStyle: "solid",
    borderColor: "#fff",
    borderWidth: 1,
    width: 430,
    height: 62,
  },
  studyPlanView: {
    position: "relative",
    backgroundColor: "#ffe4ae",
    flex: 1,
    width: "100%",
    height: 931,
  },
});

export default StudyPlan;
